# Generated by Django 3.1.2 on 2021-01-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cause', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='don_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
