# Generated by Django 3.1.2 on 2021-01-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cause', '0002_cause_don_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
