# Generated by Django 3.1.2 on 2021-01-21 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cause', '0003_cause_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
