# Generated by Django 3.1.2 on 2021-01-24 09:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cause', '0005_auto_20210123_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
