# Generated by Django 3.1.2 on 2020-10-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
