# Generated by Django 3.1.2 on 2021-01-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='first-djjr-jn', max_length=255),
            preserve_default=False,
        ),
    ]
